openapi: "3.0.0"
info:
  title: Hotel API
  version: "1.0"
  description: This is the API documentation for the Hotel service.
servers:
  - url: https://example.com/api
    description: Production server
paths:
  /hotels:
    get:
      summary: Retrieve a list of hotels
      description: Retrieves a list of hotels from the database.
      responses:
        200:
          description: A list of hotels
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Hotel"
    post:
      summary: Create a new hotel
      description: Creates a new hotel in the database.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewHotel"
      responses:
        201:
          description: The hotel was created successfully
        400:
          description: Invalid request body
        500:
          description: Internal server error
  /hotels/{id}:
    get:
      summary: Retrieve a hotel by ID
      description: Retrieves a hotel by its ID from the database.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: The hotel was retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Hotel"
        404:
          description: The hotel was not found
        500:
          description: Internal server error
    put:
      summary: Update a hotel
      description: Updates a hotel in the database.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateHotel"
      responses:
        200:
          description: The hotel was updated successfully
        400:
          description: Invalid request body
        404:
          description: The hotel was not found
        500:
          description: Internal server error
    delete:
      summary: Delete a hotel
      description: Deletes a hotel from the database.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        204:
          description: The hotel was deleted successfully
        404:
          description: The hotel was not found
        500:
          description: Internal server error
components:
  schemas:
    Hotel:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        location:
          type: string
        price:
          type: number
          format: double
    NewHotel:
      type: object
      required:
        - name
        - description
        - location
        - price
      properties:
        name:
          type: string
        description:
          type: string
        location:
          type: string
        price:
          type: number
          format: double
    UpdateHotel:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        location:
          type: string
        price:
          type: number
          format: double
